create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    username      varchar(50)  not null unique,
    password_hash varchar(72)  not null,
    created_at    timestamptz  not null default now()
);
