-- A conversation is just an identity that messages and members hang off. It
-- carries no name and no type yet: every conversation at this stage is a direct
-- one between two people. Group name, type and member role arrive in the phase
-- that adds group chats.
create table conversations (
    id         bigint generated by default as identity primary key,
    created_at timestamptz not null default now()
);

-- Who can see a conversation. Membership is its own table rather than two
-- columns on conversations, because a group has an unbounded number of members
-- and because the group phase adds a role column here.
create table conversation_members (
    id              bigint      generated by default as identity primary key,
    conversation_id bigint      not null references conversations (id),
    user_id         bigint      not null references users (id),
    joined_at       timestamptz not null default now(),

    -- The pair is what has to be unique; the id above is just a simple handle
    -- for the row. Without this a person could be added to the same
    -- conversation twice and appear in the member list more than once.
    unique (conversation_id, user_id)
);

-- Looking up "which conversations is this person in" is what the dashboard
-- does, and it reads by user_id, which the unique constraint above cannot help
-- with because that index is ordered by conversation_id first.
create index idx_conversation_members_user_id on conversation_members (user_id);

create table messages (
    id              bigint        generated by default as identity primary key,
    conversation_id bigint        not null references conversations (id),
    sender_id       bigint        not null references users (id),
    body            varchar(4000) not null,
    created_at      timestamptz   not null default now()
);

-- Every read of a conversation asks for the newest messages first and then
-- walks backwards from an id. This index answers exactly that shape, so the
-- database can jump straight to the right rows instead of sorting the whole
-- conversation each time.
create index idx_messages_conversation_id_id on messages (conversation_id, id desc);
